version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_cont"
    ports:
      - 80:80
    depends_on:
      - django_app

  django_app:
    image: django_app
    build:
      context: ./django
    container_name: "django_cont"
    ports:
      - 8001:8001
    command: gunicorn core.wsgi --bind 0.0.0.0:8001
    env_file:
      - "./django/.env"
    depends_on:
      - db

  db:
    image: postgres
    # restard: always
    container_name: "db_cont"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      # - db:/var/lib/postgresql/data
      - ./data/postgres/db:/var/lib/postgres # we will have folder data for persistence

# volumes:
#   db:
#     driver: local

    


  # db:
  #   image: Mysql
    # container_name: "db_cont"
    # environment:
      # - MYSQL_ROOT_PASSWORD=password
      # - MYSQL_DATABASE=nginxDjango_db
      # volumes: 
      #   - ./data/mysql/db:/var/lib/mysql


